FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY plates.html /usr/share/nginx/html/plates.html
COPY settings.html /usr/share/nginx/html/settings.html
COPY logs.html /usr/share/nginx/html/logs.html
